"""initial migration

Revision ID: 7e1c754467bf
Revises: 
Create Date: 2025-12-23 23:59:43.667298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1c754467bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pre_defined_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category_field', sa.String(length=64), nullable=False),
    sa.Column('date_field', sa.String(length=64), nullable=False),
    sa.Column('amount_field', sa.String(length=64), nullable=False),
    sa.Column('description_field', sa.String(length=255), nullable=True),
    sa.Column('positive_expense', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category_field', sa.String(length=64), nullable=True),
    sa.Column('date_field', sa.String(length=64), nullable=True),
    sa.Column('amount_field', sa.String(length=64), nullable=True),
    sa.Column('description_field', sa.String(length=128), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('positive_expense', sa.Boolean(), nullable=True),
    sa.Column('account_type', sa.Enum('checking', 'savings', 'credit_card', 'retirement', 'brokerage', 'real_estate', 'vehicle', 'other_asset', 'loan', name='account_type_enum'), nullable=False),
    sa.Column('retirement_type', sa.Enum('traditional_401k', 'roth_401k', 'traditional_ira', 'roth_ira', 'sep_ira', '403b', 'pension', name='retirement_type_enum'), nullable=True),
    sa.Column('initial_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('pension_monthly_benefit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pension_start_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'family_id', name='_account_family_uc')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'family_id', name='_category_family_uc')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('account_balance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'as_of_date', name='unique_account_date')
    )
    with op.batch_alter_table('account_balance_history', schema=None) as batch_op:
        batch_op.create_index('idx_account_date', ['account_id', 'as_of_date'], unique=False)

    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=64), nullable=True),
    sa.Column('field_to_match', sa.String(length=32), nullable=False),
    sa.Column('match_pattern', sa.String(length=256), nullable=False),
    sa.Column('is_transfer', sa.Boolean(), nullable=True),
    sa.Column('override_category_id', sa.Integer(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.ForeignKeyConstraint(['override_category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('is_transfer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_category_association',
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('budget_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_category_association')
    op.drop_table('transaction')
    op.drop_table('import_rules')
    op.drop_table('budget')
    with op.batch_alter_table('account_balance_history', schema=None) as batch_op:
        batch_op.drop_index('idx_account_date')

    op.drop_table('account_balance_history')
    op.drop_table('user')
    op.drop_table('category')
    op.drop_table('accounts')
    op.drop_table('pre_defined_accounts')
    op.drop_table('family')
    # ### end Alembic commands ###
