version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      FLASK_CONFIG: "config.config.DevelopmentConfig"
      SECRET_KEY: "your_secret_key_here"
      REDIS_URL: "redis://redis:6379"
    volumes:
      - ..:/app
    depends_on:
      - redis
    ports:
      - "5002:5002"  

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
