name: Tag Release on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  tag-release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # required for full git history

      - name: Extract version from branch name
        id: extract
        run: |
          BRANCH_NAME="${GITHUB_EVENT_PULL_REQUEST_HEAD_REF:-${{ github.event.pull_request.head.ref }}}"
          echo "Branch name: $BRANCH_NAME"
          if [[ "$BRANCH_NAME" =~ release/([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            VERSION="v${BASH_REMATCH[1]}"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "Branch name does not contain a valid release version."
            exit 1
          fi

      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.extract.outputs.version }}
          git push origin ${{ steps.extract.outputs.version }}

      - name: Package release artifacts
        run: |
          mkdir -p release-assets
          tar -czvf release-assets/finance-tracker-${{ steps.extract.outputs.version }}.tar.gz \
            docker_portable/docker-compose.yml \
            docker_portable/.env_default
        
      - name: Create GitHub Release with asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract.outputs.version }}
          name: "Release ${{ steps.extract.outputs.version }}"
          body: "Release triggered by merging PR from branch ${{ github.event.pull_request.head.ref }}."
          files: release-assets/*.tar.gz
